// Vulnerable: HFT-5392
void CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_53d_badSink(data);
