// Vulnerable: HFT-5315
void CWE134_Uncontrolled_Format_String__char_console_w32_vsnprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_w32_vsnprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_w32_vsnprintf_53d_badSink(data);
