// Vulnerable: HFT-5733
void CWE134_Uncontrolled_Format_String__wchar_t_console_w32_vsnprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_w32_vsnprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_w32_vsnprintf_53d_badSink(data);
