// Vulnerable: HFT-5574
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_53c_badSink(data);
