// Vulnerable: HFT-5615
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_52c_badSink(data);
