// Vulnerable: HFT-5661
extern int CWE134_Uncontrolled_Format_String__wchar_t_console_fprintf_22_badGlobal;
void CWE134_Uncontrolled_Format_String__wchar_t_console_fprintf_22_badSink(wchar_t * data)
if(CWE134_Uncontrolled_Format_String__wchar_t_console_fprintf_22_badGlobal)
fwprintf(stdout, data);
