// Vulnerable: HFT-5697
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_53d_badSink(data);
