// Vulnerable: HFT-5179
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_54d_badSink(data);
