// Vulnerable: HFT-5522
void CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_53c_badSink(data);
