// Vulnerable: HFT-5855
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54c_badSink(data);
