// Vulnerable: HFT-5307
void CWE134_Uncontrolled_Format_String__char_console_vprintf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_vprintf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_vprintf_54e_badSink(data);
