// Vulnerable: HFT-5176
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_53d_badSink(data);
