// Vulnerable: HFT-5373
void CWE134_Uncontrolled_Format_String__char_environment_vfprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_vfprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_vfprintf_53d_badSink(data);
