// Vulnerable: HFT-5173
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_snprintf_52c_badSink(data);
