// Vulnerable: HFT-5951
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_vprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_vprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_vprintf_54c_badSink(data);
