// Vulnerable: HFT-5390
void CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_w32_vsnprintf_52c_badSink(data);
