// Vulnerable: HFT-5345
void CWE134_Uncontrolled_Format_String__char_environment_printf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_printf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_printf_54d_badSink(data);
