// Vulnerable: HFT-5407
void CWE134_Uncontrolled_Format_String__char_file_fprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_fprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_fprintf_54c_badSink(data);
