// Vulnerable: HFT-5276
void CWE134_Uncontrolled_Format_String__char_console_snprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_snprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_snprintf_52c_badSink(data);
