// Vulnerable: HFT-5961
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_w32_vsnprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_w32_vsnprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_w32_vsnprintf_54c_badSink(data);
