// Vulnerable: HFT-5555
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_52c_badSink(data);
