// Vulnerable: HFT-5375
void CWE134_Uncontrolled_Format_String__char_environment_vfprintf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_vfprintf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_vfprintf_54d_badSink(data);
