// Vulnerable: HFT-5925
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_52c_badSink(data);
