// Vulnerable: HFT-5701
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54e_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54d_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54e_badSink(data);
