// Vulnerable: HFT-8896
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53c_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53b_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53c_badSink(data);
