// Vulnerable: HFT-5481
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53c_badSink(data);
