// Vulnerable: HFT-5927
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_snprintf_53c_badSink(data);
