// Vulnerable: HFT-5420
void CWE134_Uncontrolled_Format_String__char_file_printf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_printf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_printf_53c_badSink(data);
