// Vulnerable: HFT-5976
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_badSink(char * data);
void CWE15_External_Control_of_System_or_Configuration_Setting__w32_54b_badSink(char * data)
CWE15_External_Control_of_System_or_Configuration_Setting__w32_54c_badSink(data);
