// Vulnerable: HFT-5226
void CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_52c_badSink(data);
