// Vulnerable: HFT-8894
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_52c_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_52b_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_52c_badSink(data);
