// Vulnerable: HFT-5215
void CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_54d_badSink(data);
