// Vulnerable: HFT-5819
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_52c_badSink(data);
