// Vulnerable: HFT-5773
void CWE134_Uncontrolled_Format_String__wchar_t_environment_snprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_snprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_snprintf_52c_badSink(data);
