// Vulnerable: HFT-5212
void CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_vprintf_53c_badSink(data);
