// Vulnerable: HFT-5459
void CWE134_Uncontrolled_Format_String__char_file_vprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_vprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_vprintf_52c_badSink(data);
