// Vulnerable: HFT-5532
void CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_53d_badSink(data);
