// Vulnerable: HFT-5295
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_vfprintf_53d_badSink(data);
