// Vulnerable: HFT-5914
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_printf_54e_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_printf_54d_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_listen_socket_printf_54e_badSink(data);
