// Vulnerable: HFT-5798
void CWE134_Uncontrolled_Format_String__wchar_t_environment_vprintf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_vprintf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_vprintf_53c_badSink(data);
