// Vulnerable: HFT-5346
void CWE134_Uncontrolled_Format_String__char_environment_printf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_printf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_printf_54e_badSink(data);
