// Vulnerable: HFT-5419
void CWE134_Uncontrolled_Format_String__char_file_printf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_printf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_printf_52c_badSink(data);
