// Vulnerable: HFT-5423
void CWE134_Uncontrolled_Format_String__char_file_printf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_printf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_printf_54d_badSink(data);
