// Vulnerable: HFT-5725
void CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_54e_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_54d_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_54e_badSink(data);
