// Vulnerable: HFT-5857
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54e_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54d_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_54e_badSink(data);
