// Vulnerable: HFT-5869
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54c_badSink(data);
