// Vulnerable: HFT-8900
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54d_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54c_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54d_badSink(data);
