// Vulnerable: HFT-5260
void CWE134_Uncontrolled_Format_String__char_console_printf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_printf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_printf_52c_badSink(data);
