// Vulnerable: HFT-5283
void CWE134_Uncontrolled_Format_String__char_console_snprintf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_snprintf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_snprintf_54e_badSink(data);
