// Vulnerable: HFT-5577
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54d_badSink(data);
