// Vulnerable: HFT-5870
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_54d_badSink(data);
