// Vulnerable: HFT-5305
void CWE134_Uncontrolled_Format_String__char_console_vprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_vprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_vprintf_54c_badSink(data);
