// Vulnerable: HFT-5879
void CWE134_Uncontrolled_Format_String__wchar_t_file_vprintf_54d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_vprintf_54c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_vprintf_54d_badSink(data);
