// Vulnerable: HFT-5576
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_54c_badSink(data);
