// Vulnerable: HFT-5811
void CWE134_Uncontrolled_Format_String__wchar_t_environment_w32_vsnprintf_54d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_w32_vsnprintf_54c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_w32_vsnprintf_54d_badSink(data);
