// Vulnerable: HFT-5497
void CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54e_badSink(data);
