// Vulnerable: HFT-5999
void CWE176_Improper_Handling_of_Unicode_Encoding__w32_53d_badSink(wchar_t * data);
void CWE176_Improper_Handling_of_Unicode_Encoding__w32_53c_badSink(wchar_t * data)
CWE176_Improper_Handling_of_Unicode_Encoding__w32_53d_badSink(data);
