// Vulnerable: HFT-8901
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54e_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54d_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54e_badSink(data);
