// Vulnerable: HFT-5406
void CWE134_Uncontrolled_Format_String__char_file_fprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_fprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_fprintf_53d_badSink(data);
