// Vulnerable: HFT-5245
void CWE134_Uncontrolled_Format_String__char_console_fprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_fprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_fprintf_52c_badSink(data);
