// Vulnerable: HFT-5890
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54e_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54d_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54e_badSink(data);
