// Vulnerable: HFT-5482
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_53d_badSink(data);
