// Vulnerable: HFT-5450
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_vfprintf_52c_badSink(data);
