// Vulnerable: HFT-5341
void CWE134_Uncontrolled_Format_String__char_environment_printf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_printf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_printf_52c_badSink(data);
