// Vulnerable: HFT-5199
void CWE134_Uncontrolled_Format_String__char_connect_socket_vfprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_vfprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_vfprintf_54c_badSink(data);
