// Vulnerable: HFT-5454
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_vfprintf_54d_badSink(data);
