// Vulnerable: HFT-5436
void CWE134_Uncontrolled_Format_String__char_file_snprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_snprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_snprintf_53c_badSink(data);
