// Vulnerable: HFT-5820
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53c_badSink(data);
