// Vulnerable: HFT-5460
void CWE134_Uncontrolled_Format_String__char_file_vprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_vprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_vprintf_53c_badSink(data);
