// Vulnerable: HFT-5422
void CWE134_Uncontrolled_Format_String__char_file_printf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_printf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_printf_54c_badSink(data);
