// Vulnerable: HFT-6001
void CWE176_Improper_Handling_of_Unicode_Encoding__w32_54d_badSink(wchar_t * data);
void CWE176_Improper_Handling_of_Unicode_Encoding__w32_54c_badSink(wchar_t * data)
CWE176_Improper_Handling_of_Unicode_Encoding__w32_54d_badSink(data);
