// Vulnerable: HFT-5760
void CWE134_Uncontrolled_Format_String__wchar_t_environment_printf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_printf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_printf_53d_badSink(data);
