// Vulnerable: HFT-5543
void CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54c_badSink(data);
