// Vulnerable: HFT-5888
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_54c_badSink(data);
