// Vulnerable: HFT-5544
void CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_54d_badSink(data);
