// Vulnerable: HFT-5743
extern int CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_22_badGlobal;
void CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_22_badSink(wchar_t * data)
if(CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_22_badGlobal)
fwprintf(stdout, data);
