// Vulnerable: HFT-5356
void CWE134_Uncontrolled_Format_String__char_environment_snprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_snprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_snprintf_52c_badSink(data);
