// Vulnerable: HFT-5439
void CWE134_Uncontrolled_Format_String__char_file_snprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_snprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_snprintf_54c_badSink(data);
