// Vulnerable: HFT-5298
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_vfprintf_54e_badSink(data);
