// Vulnerable: HFT-5682
void CWE134_Uncontrolled_Format_String__wchar_t_console_printf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_printf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_printf_54c_badSink(data);
