// Vulnerable: HFT-5250
void CWE134_Uncontrolled_Format_String__char_console_fprintf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_fprintf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_fprintf_54e_badSink(data);
