// Vulnerable: HFT-5821
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_53d_badSink(data);
