// Vulnerable: HFT-8897
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53d_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53c_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_53d_badSink(data);
