// Vulnerable: HFT-5789
void CWE134_Uncontrolled_Format_String__wchar_t_environment_vfprintf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_vfprintf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_vfprintf_53c_badSink(data);
