// Vulnerable: HFT-5886
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_53c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_53b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_w32_vsnprintf_53c_badSink(data);
