// Vulnerable: HFT-5618
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_54c_badSink(data);
