// Vulnerable: HFT-5296
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_vfprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_vfprintf_54c_badSink(data);
