// Vulnerable: HFT-5246
void CWE134_Uncontrolled_Format_String__char_console_fprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_fprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_fprintf_53c_badSink(data);
