// Vulnerable: HFT-6043
void CWE190_Integer_Overflow__char_fscanf_add_54d_badSink(char data);
void CWE190_Integer_Overflow__char_fscanf_add_54c_badSink(char data)
CWE190_Integer_Overflow__char_fscanf_add_54d_badSink(data);
