// Vulnerable: HFT-5480
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_52c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_52b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_52c_badSink(data);
