// Vulnerable: HFT-5822
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_fprintf_54c_badSink(data);
