// Vulnerable: HFT-5279
void CWE134_Uncontrolled_Format_String__char_console_snprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_snprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_snprintf_53d_badSink(data);
