// Vulnerable: HFT-5722
void CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_vprintf_53d_badSink(data);
