// Vulnerable: HFT-5331
void CWE134_Uncontrolled_Format_String__char_environment_fprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_fprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_fprintf_54c_badSink(data);
