// Vulnerable: HFT-5617
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_vfprintf_53d_badSink(data);
