// Vulnerable: HFT-5850
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_snprintf_52c_badSink(data);
