// Vulnerable: HFT-5868
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_53d_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_53c_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_file_vfprintf_53d_badSink(data);
