// Vulnerable: HFT-5496
void CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_listen_socket_printf_54d_badSink(data);
