// Vulnerable: HFT-5330
void CWE134_Uncontrolled_Format_String__char_environment_fprintf_53d_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_environment_fprintf_53c_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_environment_fprintf_53d_badSink(data);
