// Vulnerable: HFT-5451
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_53c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_file_vfprintf_53b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_file_vfprintf_53c_badSink(data);
