// Vulnerable: HFT-5745
void CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_52c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_52b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_environment_fprintf_52c_badSink(data);
