// Vulnerable: HFT-8899
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54c_badSink(wchar_t * data);
void CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54b_badSink(wchar_t * data)
CWE124_Buffer_Underwrite__wchar_t_declare_memmove_54c_badSink(data);
