// Vulnerable: HFT-5231
void CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_54e_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_54d_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_connect_socket_w32_vsnprintf_54e_badSink(data);
