// Vulnerable: HFT-5264
void CWE134_Uncontrolled_Format_String__char_console_printf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_printf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_printf_54c_badSink(data);
