// Vulnerable: HFT-5281
void CWE134_Uncontrolled_Format_String__char_console_snprintf_54c_badSink(char * data);
void CWE134_Uncontrolled_Format_String__char_console_snprintf_54b_badSink(char * data)
CWE134_Uncontrolled_Format_String__char_console_snprintf_54c_badSink(data);
