// Vulnerable: HFT-5699
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54c_badSink(wchar_t * data);
void CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54b_badSink(wchar_t * data)
CWE134_Uncontrolled_Format_String__wchar_t_console_snprintf_54c_badSink(data);
