// Vulnerable: GO-001 (exec sh -c user cmd)
exec.Command("sh", "-c", cmd).Run()
// Vulnerable: GO-002 (bash -c with concatenation)
exec.Command("bash", "-c", "ping -c 1 "+host).Run()
// Vulnerable: GO-003 (unsafe ORDER BY fragment)
q := "SELECT * FROM users ORDER BY " + order
// Vulnerable: GO-004 (reflection method by user name)
reflect.ValueOf(handler).MethodByName(method).Call(nil)
// Vulnerable: GO-005 (plugin load from input)
plugin.Open(pluginName)
// Vulnerable: GO-006 (JS eval via VM)
vm.RunString(script)
// Vulnerable: GO-007 (template parse from user input)
template.Must(template.New("x").Parse(tpl))
// Vulnerable: GO-008 (exec tool from payload)
exec.Command(tool).Run()
// Vulnerable: GO-009 (goroutine leak without context cancellation)
go func() { for { doWork() } }()
// Vulnerable: GO-010 (path traversal via filepath.Join)
target := filepath.Join(root, userInput)
// Vulnerable: GO-011 (SSRF via http.Get untrusted URL)
http.Get(userInputURL)
// Vulnerable: GO-012 (unsafe pointer arithmetic)
ptr2 := unsafe.Pointer(uintptr(ptr) + offset)
// Vulnerable: GO-013 (weak crypto MD5/SHA1)
md5.New()
sha1.New()
// Vulnerable: GO-014 (open redirect from query parameter)
http.Redirect(w, r, r.URL.Query().Get("next"), http.StatusFound)
// Vulnerable: GO-015 (log injection without CR/LF sanitization)
log.Printf("User: %s", userInput)
// Vulnerable: GO-016 (hardcoded credentials)
const apiKey = "prod-api-key-12345"
// Vulnerable: GO-017 (data race on shared variable without mutex)
counter++
go func() { counter = counter + 1 }()
// Vulnerable: GO-018 (JWT alg validation bypass in Keyfunc)
jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) { return key, nil })
// Vulnerable: GO-019 (DB rows leak without defer Close)
rows, _ := db.Query(query)
for rows.Next() { scan(rows) }
// Vulnerable: GO-020 (insecure TLS config)
tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
// Vulnerable: GO-021 (unclosed file descriptor)
f, _ := os.Open(path)
io.ReadAll(f)
// Vulnerable: GO-022 (improper output encoding / XSS)
fmt.Fprintf(w, userInput)
// Vulnerable: GO-023 (missing request body limit)
body, _ := ioutil.ReadAll(r.Body)
// Vulnerable: GO-024 (debug endpoint in production)
import _ "net/http/pprof"
// Vulnerable: GO-025 (gRPC missing auth checks)
func (s *Server) Transfer(ctx context.Context, req *pb.TransferRequest) (*pb.TransferReply, error) { return s.svc.Transfer(ctx, req) }
// Vulnerable: GO-026 (Zip Slip extraction)
targetPath := filepath.Join(dest, f.Name)
// Vulnerable: GO-027 (proxy header injection)
req.Header = r.Header
// Vulnerable: GO-028 (unsafe reflect deep copy)
reflect.ValueOf(dst).Elem().Set(reflect.ValueOf(src).Elem())
// Vulnerable: GO-029 (hardcoded root CAs in code)
const rootPEM = "-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----"
pool.AppendCertsFromPEM([]byte(rootPEM))
// Vulnerable: GO-030 (gRPC without MaxRecvMsgSize)
srv := grpc.NewServer()
// Vulnerable: GO-031 (insecure randomness with math/rand)
b[i] = byte(rand.Intn(256))
// Vulnerable: GO-032 (unbounded JSON unmarshal from request body)
raw, _ := io.ReadAll(r.Body)
json.Unmarshal(raw, &payload)
// Vulnerable: GO-033 (GORM raw SQL injection)
db.Raw("SELECT * FROM users WHERE name = '" + userName + "'").Scan(&users)
// Vulnerable: GO-034 (bypass XSS protection via template.HTML)
unsafeHTML := template.HTML(userInput)
fmt.Fprint(w, unsafeHTML)
// Vulnerable: GO-035 (sensitive info leak in error messages)
return fmt.Errorf("db=%s secret=%s path=%s", dsn, apiKey, filePath)
// Vulnerable: GO-036 (unsafe CGO buffer handling)
ptr := unsafe.Pointer(uintptr(cptr) + offset)
C.process(ptr)
// Vulnerable: GO-037 (unsafe map assignment from JSON without key validation)
for k, v := range incomingMap { targetMap[k] = v }
// Vulnerable: GO-038 (improper XML entity handling in custom parser)
xmlParser := customxml.NewParser()
xmlParser.Parse(rawXML)
// Vulnerable: GO-039 (Regex DoS)
regexp.MustCompile(userRegex).MatchString(longUserInput)
// Vulnerable: GO-040 (hardcoded JWT secret)
jwtKey := []byte("my-secret-key")
