# Vulnerable: INF-088
apiVersion: v1
kind: Service
metadata:
  name: tiller-deploy
  labels:
    app: helm
    name: tiller
spec:
  type: ClusterIP
  selector:
...
    protocol: TCP
    targetPort: tiller
