# Vulnerable: INF-030
apiVersion: v1
kind: Pod
metadata:
  name: pod-drop-none
spec:
  containers:
    - name: main
      image: fedora
      command: ["/bin/sleep", "999999"]
# kubectl exec -it pod-drop-none -- bash
...
# pscap
## Notice net_raw capability
