# Vulnerable: INF-041
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kubelet
    tier: control-plane
  name: kube-controller-manager-disabled
  namespace: kube-system
spec:
...
      path: /etc/pki
    name: pki
