# Vulnerable: INF-060
apiVersion: v1
kind: Pod
metadata:
  name: hello-apparmor-1
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello1: dummy
    container.apparmor.security.beta.kubernetes.io/hello2: dummy
spec:
  containers:
  - name: hello1
...
      - name: ubuntu-1-container
        image: 0x010/ubuntu-w-utils:latest
